baseurl = "http://keichi.net/"
languageCode = "ja-jp"
title = "Keichi Takahashi"
author = "Keichi Takahashi"
copyright = "&copy; 2015 Keichi Takahashi. All Rights Reserved."

[params]
    twitter = "_keichi_"
    github = "keichi"
    linkedin = "keichi"
    facebook = "keichi.t"
    ga_api_key = "UA-59307512-1"
    bio = "is a software developer, hardware hacker and a beer lover. He believes in the power of code."

