baseurl: "https://keichi.net/"
title: "Keichi Takahashi"
copyright: "&copy; 2019 Keichi Takahashi"
theme: literati
defaultContentLanguage: ja
disableHugoGeneratorInject: true
hasCJKLanguage: true
enableGitInfo: true
pygmentsCodefences: true
pygmentsUseClasses: true

blackfriday:
  fractions: false
  extensions:
    - joinLines

menu:
  main:
    - name: About
      identifier: about
      url: /
    - name: CV
      identifier: cv
      url: /cv_takahashi.pdf
    - name: Blog
      identifier: blog
      url: /post/

params:
  author: Keichi Takahashi
  email: keichi.t@me.com
  twitter: _keichi_
  github: keichi
  googleAnalytics: UA-59307512-1
