baseurl = "https://blog.app.keichi.net/"
languageCode = "ja-jp"
title = "Keichi Takahashi"
copyright = "&copy; 2016 Keichi Takahashi. All Rights Reserved."
theme = "vienna"

[params]
    twitter = "_keichi_"
    github = "keichi"
    linkedin = "keichi"
    facebook = "keichi.t"
    ga_api_key = "UA-59307512-1"
    disqus = "keichi"
    author = "Keichi Takahashi"
    avatar = "/images/avatar.jpg"
    contact = "mailto:keichi.t@me.com"
    bio = "A software developer, hardware hacker and a beer lover. Keichi believes in the power of code."
    subtitle = "is a software developer, hardware hacker and a beer lover. He believes in the power of code."

